name: auto-demonstrator-ci
run-name: ${{ github.actor }} running on trigger
on: [repository_dispatch]
  
jobs:
  echo_work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print out
        run: echo "Job ran"
    
